In [48]:
import pandas as pd 
import numpy as np
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split

In [49]:
df = pd.read_csv('bnb-usd.csv')
df.head(5)

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits
0,2017-11-09 00:00:00+00:00,2.05314,2.17423,1.89394,1.99077,19192200,0.0,0.0
1,2017-11-10 00:00:00+00:00,2.00773,2.06947,1.64478,1.79684,11155000,0.0,0.0
2,2017-11-11 00:00:00+00:00,1.78628,1.91775,1.61429,1.67047,8178150,0.0,0.0
3,2017-11-12 00:00:00+00:00,1.66889,1.67280,1.46256,1.51969,15298700,0.0,0.0
4,2017-11-13 00:00:00+00:00,1.52601,1.73502,1.51760,1.68662,12238800,0.0,0.0

In [50]:
df.tail(20)

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits
2379,2024-05-15 00:00:00+00:00,566.707031,587.421509,561.127258,582.074341,1895100260,0.0,0.0
2380,2024-05-16 00:00:00+00:00,582.100159,586.436340,565.762329,569.190247,1911862000,0.0,0.0
2381,2024-05-17 00:00:00+00:00,569.190247,584.666016,568.836731,581.178345,1557134929,0.0,0.0
2382,2024-05-18 00:00:00+00:00,581.178345,581.987183,575.018555,580.481140,1358737176,0.0,0.0
2383,2024-05-19 00:00:00+00:00,580.481567,581.876709,572.369629,574.631653,1298887094,0.0,0.0
2384,2024-05-20 00:00:00+00:00,574.631653,601.563843,569.523560,600.616333,2145457267,0.0,0.0
2385,2024-05-21 00:00:00+00:00,600.601074,629.861084,593.932739,618.420471,3564986916,0.0,0.0
2386,2024-05-22 00:00:00+00:00,618.420471,625.566284,610.546021,614.671875,2138536549,0.0,0.0
2387,2024-05-23 00:00:00+00:00,614.671875,616.524475,581.954102,598.670837,2631566566,0.0,0.0
2388,2024-05-24 00:00:00+00:00,598.670837,604.314880,588.893982,600.225891,1778282198,0.0,0.0
2389,2024-05-25 00:00:00+00:00,600.226624,606.367310,599.607239,602.194458,1392399167,0.0,0.0
2390,2024-05-26 00:00:00+00:00,602.194458,604.830078,598.695862,599.825928,1372657185,0.0,0.0
2391,2024-05-27 00:00:00+00:00,599.825928,613.388184,599.700745,603.526428,1691663828,0.0,0.0
2392,2024-05-28 00:00:00+00:00,603.526428,604.985107,593.716187,601.213257,1852329404,0.0,0.0
2393,2024-05-29 00:00:00+00:00,601.213257,602.931519,592.966614,594.972046,1642696946,0.0,0.0
2394,2024-05-30 00:00:00+00:00,594.972534,601.665039,586.557678,595.026794,1737524745,0.0,0.0
2395,2024-05-31 00:00:00+00:00,595.026794,598.423645,589.774841,593.522339,1590349553,0.0,0.0
2396,2024-06-01 00:00:00+00:00,593.522339,607.582886,592.680603,601.304199,1520074486,0.0,0.0
2397,2024-06-02 00:00:00+00:00,601.304138,604.978088,596.164795,603.026611,1667233984,0.0,0.0
2398,2024-06-03 00:00:00+00:00,603.020935,634.066345,601.448730,624.983276,2343878912,0.0,0.0

In [51]:
df.columns

Index(['Date', 'Open', 'High', 'Low', 'Close', 'Volume', 'Dividends',
       'Stock Splits'],
      dtype='object')

In [52]:
df.drop([ 'Open', 'High', 'Low',  'Dividends', 'Stock Splits', 'Volume'], inplace = True, axis = 1)

In [53]:
df['time'] = pd.to_datetime(df['Date'])
df['formatted_time'] = df['time'].dt.strftime('%d-%m-%Y')
df['formatted_time']

0       09-11-2017
1       10-11-2017
2       11-11-2017
3       12-11-2017
4       13-11-2017
           ...
2394    30-05-2024
2395    31-05-2024
2396    01-06-2024
2397    02-06-2024
2398    03-06-2024
Name: formatted_time, Length: 2399, dtype: object

In [54]:
df.drop([ 'Date', 'time'], inplace = True, axis = 1)

In [55]:
df

           Close formatted_time
0       1.990770     09-11-2017
1       1.796840     10-11-2017
2       1.670470     11-11-2017
3       1.519690     12-11-2017
4       1.686620     13-11-2017
...          ...            ...
2394  595.026794     30-05-2024
2395  593.522339     31-05-2024
2396  601.304199     01-06-2024
2397  603.026611     02-06-2024
2398  624.983276     03-06-2024

[2399 rows x 2 columns]

In [63]:
import pandas_ta as ta
 
df['SMA'] = ta.sma(df['Close'], length=5) 
df['EMA'] = ta.ema(df['Close'], length=5) 
df['RSI'] = ta.rsi(df['Close'], length=14)

In [65]:
df.fillna(0, inplace = True)

In [66]:
new_df = df.copy()

In [69]:
X = new_df.drop(['Close', 'formatted_time'], axis = 1).values
Y = new_df['Close'].values

In [72]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

In [73]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

In [74]:
rf = RandomForestRegressor()
 
param_grid = {
    'n_estimators': [50, 100, 150, 200, 250, 300]
}
grid_search_rf = GridSearchCV(estimator=rf, param_grid=param_grid, cv=3)
grid_search_rf.fit(X_train, y_train)

GridSearchCV(cv=3, estimator=RandomForestRegressor(),
             param_grid={'n_estimators': [50, 100, 150, 200, 250, 300]})

In [75]:
best_rf = grid_search_rf.best_estimator_
best_rf

RandomForestRegressor(n_estimators=200)

In [76]:
y_pred_rf = best_rf.predict(X_test)

array([269.49240028, 311.05429993,  12.64619291, 298.4439624 ,
       310.89083801,  10.72428505, 412.00617722, 243.44063812,
       389.84866547,  30.44300324, 234.2395401 ,  10.3982472 ,
       218.28848427, 537.41770142, 205.43152451, 284.17972931,
        13.84207033, 342.04828964, 389.93812042, 377.9700679 ,
        23.14603919, 212.69941467,  23.31333476, 213.46875542,
       294.06224319,  23.93632927, 362.31590652, 302.53931015,
       377.01509354, 239.29625816, 290.72716553,  30.05919868,
       323.50424469, 140.77760376, 129.40625023, 309.81329086,
        14.88815508,   9.25063257,  18.3057187 ,  17.24304904,
         6.34145166, 400.10805725,  14.7970037 ,  31.41898348,
         9.10864037,  30.49130333, 312.54101807, 210.76271629,
       307.26790787,  28.20147214,  27.0582642 , 286.27447098,
         6.10386303, 305.73369812, 285.66168945, 407.17788986,
       563.58656128, 468.07298508, 301.45068344, 422.41139725,
       316.1171698 ,  17.51718543, 329.84935867,  15.44059838,
       269.85736664,  19.65845933, 560.02171265,   5.87095717,
       241.53958504,  27.11193094, 400.89290695, 273.88029633,
       312.15362915, 240.84514252,  13.61900434,  12.67664038,
       231.69800766,  14.30965189,  12.86578916, 558.25986328,
        14.06129985,  13.60405514, 286.51309464,  13.0503517 ,
        27.44237626,  13.04799612,  27.99313697,  14.67049541,
        11.19514552,   5.19888187, 226.7667112 ,  28.50447282,
        12.12192873, 247.86644058, 376.58158813, 583.98891174,
        18.13907233, 356.32492676, 466.98361191, 226.56926765,
       617.81956421, 432.8240033 ,  14.57600743, 314.83657059,
       305.83935104, 388.71951248, 238.61079155,  12.52932156,
       241.47541397, 472.69713699,  20.26168071, 292.33949249,
       306.72477707, 273.67550507,  17.80843632,   6.54154727,
       303.84771469, 304.22721207,  40.29025654,  27.48299987,
        27.43483288, 373.46980606, 233.71342697, 400.53230728,
       309.29189056,  19.50711277,  21.86362569, 580.77108459,
        18.28258514,  12.82204488, 212.27237823,  33.33537278,
       306.83987122,   9.62341012,  27.75971363, 407.12444778,
       303.6544809 ,  16.45980065, 247.10394135,  21.7127772 ,
        30.64484284, 325.86301407, 314.09784592, 559.1667865 ,
        40.99330366, 503.84003769, 243.58763824, 599.47387299,
       242.91113281,   9.08232245, 408.24532593, 212.34415833,
        22.488152  ,  11.10268091, 364.68799072,  14.25616071,
        13.69559826,  16.33164651,  13.04771073, 415.231371  ,
       240.28875916,  17.36737093,  28.39971959,   2.72487163,
        29.45466348, 311.93376801, 477.85298477,  14.98048526,
         5.91779027,  12.25071153,   5.68670057, 315.34852325,
       286.03258209,  16.4259524 ,  10.64992978,  16.26174354,
        13.00060471,  32.64052231, 264.67611313,  20.60180202,
       302.00455551,   9.6527304 ,   5.98899137, 208.6337751 ,
       581.56217407,  17.45795412, 482.12520279, 326.97363922,
        16.83623394, 248.95016975, 343.18676254,   6.52630852,
       521.38618973,  21.80948429, 601.53116974,   9.18587789,
         9.84649908, 262.60550476, 293.87264572, 423.93011993,
       238.14111855,  43.86162477,  16.23420767, 486.97575943,
       227.86469582,  23.08333508, 262.09259987,  11.00145142,
         5.86330067,  11.95764149, 422.4396347 ,   7.17840815,
        28.35510773, 600.44115204,  12.70806427, 412.09281723,
       321.37739059, 609.80897125, 572.89296875,  15.52147999,
        16.46590642,   6.08702139, 558.97695404, 330.44796967,
        27.87676184, 284.76349838,  30.05765395,  24.34523743,
        16.27056558, 519.23676178, 486.20852249, 265.2706266 ,
        16.50475942, 289.79342026,  12.33218223,  15.12801499,
       284.17065765,   4.66870534, 583.31727844,  19.49449575,
        13.70314378, 348.91196716, 323.18230652,  11.64276073,
        22.27383836, 242.58493301,  19.96741405, 227.08541206,
       221.83390152,  18.73762413,   5.1900846 ,  21.56477517,
         9.62096565, 404.73032944, 270.00995522, 542.48024994,
       276.67175034,   9.93182426,  28.0038518 ,   8.82572309,
        20.41334163,  21.02196188,   8.51167581, 130.97886192,
       248.91183228, 560.2404837 ,  17.04813859,   9.28936374,
        11.94997746,   9.8083841 ,   9.42333795, 251.82649956,
        16.82223581, 234.86329178,  27.63765103, 213.25624374,
        12.43885253,  14.76296978, 317.3238826 , 551.35443588,
         6.49757649, 327.64290863, 243.44853264,  13.85234131,
        15.60974168,   9.55418906,   5.93594748,  14.82866188,
        31.18394815, 244.48161774,  23.07441599,  24.55319037,
       272.26362564,  23.63428332,  16.99680413,  13.44470026,
        30.97170145, 247.57170601, 296.61997849,   9.98346046,
        32.42966873,  16.9049263 , 238.04235298,  22.52324245,
         8.35692781, 307.09645477, 424.36812241,  15.47128414,
       317.1379837 ,   9.57814187, 581.82322693, 277.5565538 ,
        10.7643866 , 402.120392  , 292.12731049,  16.17047928,
       322.47133438,  11.89873593, 363.67308212, 364.20127304,
       318.57720261,  17.4616173 , 374.57733917,  11.03276388,
       214.55104355,  10.49383872,  21.30394587,   9.25752753,
       309.69416763, 323.61433136,  16.24520338, 287.54785019,
       405.97033829, 352.00868774, 398.02407425,  10.48302624,
       215.071633  , 246.20054565, 313.23619934,   9.88496656,
        11.83561227,  13.66101441,   9.81752071, 277.52696335,
       335.28754501, 305.44739777,  24.50919373,   6.20590848,
       132.22132217, 285.68391357, 555.54229797,  30.634821  ,
        16.22129334,  16.37644763, 588.47117981,  27.59817536,
        15.50022093, 599.53403656,  28.34523075, 298.54459732,
       241.46315544,   1.92535186,  14.73275436, 328.87069641,
       244.69963547,  22.58969929,  16.88449641, 244.87702385,
        13.56507331,   6.68088887, 361.19838181, 248.64505768,
       368.47018112,  11.23951145,  14.67518868, 328.43988525,
        32.92899837, 264.2784404 , 234.09999451,  15.17804835,
        28.95534964, 488.6940419 , 395.1658078 ,   9.57264916,
       383.50386093, 491.54745117,  19.02190797, 402.87009277,
       283.60520432, 293.000177  ,  16.132077  ,  17.50171885,
        30.63104967, 244.43168678,   9.40227149,  14.31047586,
       302.7098996 ,  12.23970651,   2.50481947,  41.09000462,
       650.13369446,  15.17072238, 244.73399742,  17.05167611,
        13.87666276,   9.82462546,  13.41964654, 477.75431335,
       337.21757812, 298.52834091,  30.05818507,  20.87170104,
        12.26567077,   9.17238559, 312.55818344, 309.86814774,
        20.21460187, 565.7356665 ,  14.15970392,  17.84566863,
         9.22698116,  18.04570865, 401.46401917,   5.12499907,
       237.45080261,  17.38632085, 238.17258659,  17.3371889 ,
        14.39714177,   6.61717342, 390.12871994,  15.71315537,
       215.62274742,  13.18197954, 273.398806  , 239.53096893,
       270.38469223, 304.44649033,  11.00792043,  23.91873077,
        23.56257727,  28.71289044, 215.08227844, 625.64177368,
        33.85528126, 319.77910324,  14.32963632, 214.79357506,
        10.10401113,  34.03494263, 290.33494263, 315.53098526,
        33.96712852,   9.55350521,  14.6738989 , 337.12526199,
        10.05546697, 554.51486923,  23.98727911, 277.0612027 ,
        26.25034641,  21.97351193, 326.97342331, 279.66470871,
       246.665783  , 655.22268646,  17.76173195,  29.47452583,
       285.02492569,   9.69679102, 268.1438559 , 304.25478775,
         5.27336975,  20.61736884, 230.73404808, 280.08123749,
        13.59869049,  14.56475075,   6.02446642,  16.34275479])

In [77]:
rf_metrics = {
    'RMSE': np.sqrt(mean_squared_error(y_test, y_pred_rf)),
    'MSE': mean_squared_error(y_test, y_pred_rf),
    'MAE': mean_absolute_error(y_test, y_pred_rf),
    'R2': r2_score(y_test, y_pred_rf)
}
print(rf_metrics)

{'RMSE': 8.496377661131993, 'MSE': 72.18843336058275, 'MAE': 3.1754283514395354, 'R2': 0.9978122599131659}

In [79]:
data = df [len(df) - 15:]

In [ ]:
for i in range(2):
    sma = ta.sma(data['Close'], length=5).iloc[-1]
    ema = ta.ema(data['Close'], length=5).iloc[-1]
    rsi = ta.rsi(data['Close'], length=14).iloc[-1]
    # sma_5, ema_5, rsi_14 = scaler.fit_transform(np.array([sma, ema, rsi]).reshape(-1, 1))
    # new_close = best_rf.predict([[0.163528, 0.0, 0.0, 0.0, 1.0, 0.0, sma_5[0], ema_5[0], rsi_14[0]]])
    new_close = best_rf.predict([[sma, ema, rsi]])
    print(new_close)
    new_row = pd.DataFrame({"Close": new_close, "formatted_time" : "0", "SMA" : sma, "EMA" : ema, "RSI" : rsi})
    data = pd.concat([data, new_row], ignore_index= True)

[629.37156097]
[645.69927185]
[652.99732025]
[655.68986511]
[653.96038605]
[655.63752747]
[655.63752747]
[655.63752747]
[655.63752747]
[655.63752747]

In [81]:
import pickle 
with open('bnb.pkl', 'wb') as f:
    pickle.dump(best_rf, f)